Restore work language list #175
murdos/musicbrainz-userscripts pull request #536
Opened 2023-06-29 15:05 UTC by jesus2099

Load **language list** from `/release/add` page, as it is no longer available from `/work/create` page.

2023-06-29 16:08 UTC, kellnerd requested changes
I think I had once tried to adapt this code to use the new work language select input but failed miserably. Clever idea to simply use the select input from the release page!
The only caveat which I can see with this approach is that [no lyrics] is missing. You could manually inject this one entry if you want, but it is also very useful as is already.

More important is the work submission code which also has to be adapted since the field name has changed from `language_id` to `languages.#` as multiple lyric languages are supported now:

[These lines](https://github.com/murdos/musicbrainz-userscripts/pull/536/files#diff-7778dd3ca361371e4b03ab85e352df89b6d713c16a2fa184d7cb5b7ca3045d95L1102-L1104) have to be replaced with the following (successfully tested):

```js
                    if (kind === 'type') {
                        data += `&edit-work.${kind}_id=${$obj.val()}`;
                    } else if (kind === 'language') {
                        data += `&edit-work.languages.0=${$obj.val()}`;
                    }
```

2023-06-29 18:39 UTC, jesus2099 commented
> the field name has changed from `language_id` to `languages.#`

Yes I saw that when testing the script.
I fixed and force pushed, maybe at the same time as your remark.

Thanks for all your helps.
I will read them all now and check them later. 😁👍

2023-06-29 18:41 UTC, jesus2099 commented on batch-add-recording-relationships.user.js
> +            .append($(`select#language option[value]`, nodes))
No reasons, I just didn't know how that library worked and tried some random things. 🤣

2023-06-29 18:42 UTC, jesus2099 commented
Currently [being tested](https://community.metabrainz.org/t/edit-notes-for-batch-add-performance-of-relationships/642993/27?u=jesus2099)  and several fixes are planned.

2023-06-29 18:55 UTC, jesus2099 commented
> Clever idea to simply use the select input from the release page!

I just mimicked how it was done, I would have not found it alone, maybe. :)

But now I will call `/work/create?edit-work.languages.0=486` to get the full work language list, including `[No lyrics]`, **properly localised**!

2023-06-29 22:31 UTC, jesus2099 commented on batch-add-recording-relationships.user.js
> +            .append($(`select#language option[value]`, nodes))
I have added this as part of my second commit (13ff88e3356e1976c780451a4703a6be153ec3f2).
I hope I am not breaking anything with that change request system.

2023-06-29 23:33 UTC, jesus2099 commented
I have changed all requested stuff, @kellnerd. :)

2023-06-30 09:23 UTC, kellnerd commented on batch-add-recording-relationships.user.js
> +            .append($(`select#language option[value]`, nodes))
Excellent, I hadn't realized that `zxx` was already there, just buried in the lower section of the list and under a different description :+1:

2023-06-30 09:28 UTC, kellnerd approved these changes
I think this PR is ready to be released

*Edit*: I'll wait with merging until #535 is ready to avoid a potential version conflict.

2023-06-30 10:32 UTC, jesus2099 commented
For info, instead of work language list's `[No lyrics]` we have the release language list's `[No linguistic content]` which has the same key, anyway.

I prefer that that hard-coding `[No lyrics]` in the code, that would slightly _break_ language consistency for non-English MB editors. :)

2023-06-30 16:11 UTC, jesus2099 commented
I guess it's easier to merge this one. And then to merge #535.
Isn't it?

2023-06-30 16:24 UTC, kellnerd commented
Sure, I was just wondering about the version number, of which I don't really understand the fourth component 2023.6.30.**19** and which version the other PR will get.
But maybe I should simply merge this PR now and you can assign the "final" version of #535 a ".1" as the fourth number again like 2023.6.31.1 (fake date) or 2023.7.1.1 since that will probably the last release for a few months/years again.

2023-06-30 16:27 UTC, jesus2099 commented
19 was for 00:19.
I think currently, timestamp for the other PR is more recent, so I think it's easier to merge here first, then the other. 😉

2023-06-30 16:28 UTC, merged